### PR TITLE
python3

### PR DESCRIPTION
**Pull request by jpgimenez**

### CODE REVIEW

**Comment by avollkopf** [comment]
Most likely some additional work in string handling required:
I get this error, but could not figure out from where exactly. Probably some variables require handling as byte or string (or encoding?)
"ERROR - Exception lcdjob: argument for 's' must be a bytes object"

**Comment by avollkopf** [comment]
After some segmentation of the code I was able to identify the issue (smaller than initially expected). The function get_ip requires only a minor change to be compatible with python3

```
def get_ip(interface):

    ip_addr = "Not Connected"

    so = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

    try:

        ip_addr = socket.inet_ntoa(fcntl.ioctl(so.fileno(), 0x8915, struct.pack('256s', bytes(interface.encode())[:15]))[20:24])

    finally:

        pass

    return ip_addr

```

The parameter interface needs to be converted to bytes and the plugin is working under python3 on my system.

@jpgimenez: My proposal is that you update your request with this change unless you want me to open a second pull request.

**Comment by JamFfm** [comment]
Hi avollkopf,
it will take me another 2 or 3 weeks to test and check the changes. 
Especially the python 3 migration has to be done. Other than that I added a sensor mode which shows all the sensor data of a selectable sensor Type. The bad point is that a change in the core.py file has to be done. I am not sure if that effects other addons. I will send the changes. It is not based on the python 3 mig Version. 

[LCDDisplay with sensormode.zip](https://github.com/JamFfm/craftbeerpiLCD/files/5081125/LCDDisplay.with.sensormode.zip)

I have some questions about the changes:
Does the Python version also run in 2.7? I think most CBPi users still have 2.7
If not, we should open a new branch.
Your changes will only take effect if you use PID Boil and the iSpindel plug-in. If you don't use these special configurations, the addon will continue to run as before?

Thank you very much to help improve the addon!!!

**Comment by avollkopf** [comment]
Hi JamFfm, I have tested my changes so far only on python3 but can do some tests on python2.

**Comment by avollkopf** [comment]
Hi, I tested it on python2 and it is not really working. Status is working as long as A00 is selected. But that'S it. Most likely the differences in unicode handling between py2 and py3

**Comment by avollkopf** [comment]
@JamFfm I tested a little more and it seems to be that you will just need to change import i2c to import .i2c and modify the get_ip function as mentioned above for python3 compatibility. In this case, the plugin is also running on python2. I will try to incorporate my modifications that we have the additional functions running under python2 and 3

**Comment by JamFfm** [comment]
Hi
Sounds good. 
Thanks for your contribution. 

Jan


Von meinem iPhone gesendet

Grüße Jan Battermann

**Comment by avollkopf** [comment]
@JamFfm Hi, I was now basically using your code with the two minor changes and added the gravity display for the fermenter and the hop timer for boiling. The display function was working on my pi under python2 and python3. The changes are uploaed to my repo and should be automatically available in my pull request (#6). No changes in the core module are required for these changes. 

Regards, Alex

**Comment by JamFfm** [comment]
changes are implemeted in master. Thank you very much.

**Pull request closed without merging**
